// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type ReadResponse struct {
	Data *string `json:"data,omitempty"`
}

type SubmitResponse struct {
	Commitment *string `json:"commitment,omitempty"`
	Height     *string `json:"height,omitempty"`
}
